# 项目相关配置
fuce:
  #名称
  name: v2
  #版本
  version: 3.7
  #版权年份
  copyrightYear: 2018
  #头像上传路径
  profile: D:/profile/
  #地址是否放入项目static目录，如果未Y 放入static。 profile配置失效
  isstatic: Y
  #开启存放静态文件夹后目录
  isroot_dir: static/images_upload/
  #邮件功能
  #邮箱发送smtp
  email_smtp: smtp.sina.com
  #邮箱发送端口
  email_port: 465
  #发送邮箱登录账号
  email_account: 1@sina.com
  #发送邮箱登录密码
  email_password: 1
  #实例演示开关 启动该模式删除增加修改会弹出演示模式提示框
  demoEnabled: false
  #漂亮得拖动验证码 默认false普通验证码、true滚动验证码
  rollVerification: true
#tomcat config
server :
  port : 8080
  ##项目名字配置
  #servlet : 
  #  context-path : /demo
  tomcat :
    max-threads : 128
    min-spare-threads : 5
    uri-encoding : UTF-8
    #shiro 报错修改的地方
    max-connections: 200000
    max-http-post-size: 9000000
spring :
  # 环境 dev|test|prod
  profiles :
    active : dev
    #引入其他配置文件，例如ftpHX 未配置文件application-ftpHX.yml
    #include: ftpHX,ftpCloud
  servlet:
    multipart:
      max-request-size: 100MB
      maxFileSize : 10MB
        #shiro 报错修改的地方
    max-connections: 200000
    max-http-post-size: 9000000
    # 服务模块
  devtools:
    restart:
      # 热部署开关
      enabled: true
  mvc:   #静态文件
    static-path-pattern : /static/**
  #模板引擎
  thymeleaf:
    model: HTML5
    prefix: classpath:/templates/
    suffix: .html
    #指定编码
    encoding: utf-8
    #禁用缓存 默认false
    cache: false
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
#mybatis:
#  #配置mapper的扫描，找到所有的mapper.xml映射文件
#  mapperLocations : classpath*:mybatis/*/*.xml
#  #mybatis提供三种sql执行器，分别是SIMPLE、REUSE、BATCH。
#  executor-type : reuse
#  #搜索指定包别名
#  typeAliasesPackage : com.*.model
#  #该配置项就是指将带有下划线的表字段映射为驼峰格式的实体类属性。
#  configuration :
#    map-underscore-to-camel-case : true
#pagehelper分页插件
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql
#七牛云配置
oss:
  qiniu:
    #对应存储空间的访问域名
    domain: q0stnsal9.aaa.bbb.com
    #accessKey密钥
    accessKey: 5o-rVbYF111C
    #secretKey秘钥
    secretKey: C9TETPDFHDj38d
    #bucket是创建的存储空间名
    bucket: test-img