# 项目相关配置
fuce:
  #名称
  name: Fc
  #版本
  version: 1.0
  #版权年份
  copyrightYear: 2018
  #头像上传路径
  profile: D:/profile/
#tomcat config
server :
  port : 8080
  ##项目名字配置
  #servlet : 
  #  context-path : /demo
  tomcat :
    max-threads : 128
    min-spare-threads : 5
    uri-encoding : UTF-8
spring :
  # 环境 dev|test|prod
  profiles :
    active : dev
  servlet:
    multipart:
      max-request-size: 100MB
      maxFileSize : 10MB
  mvc:   #静态文件
    static-path-pattern : /static/**
  thymeleaf:
    model: HTML5
    prefix: classpath:/templates/
    suffix: .html
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
mybatis :
  mapperLocations : classpath*:mybatis/*/*.xml
  executor-type : reuse
  type-aliases-package : com.*.model
  configuration :
    map-underscore-to-camel-case : true
#pagehelper分页插件
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql